[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tracing = "0.1.41"
anyhow = "1"
thiserror = "2"
tokio = "1"
reqwest = { version = "0.12", default-features = false }
dir-extra = { path = "crates/dir-extra" }
http-extra = { path = "crates/http-extra" }
tempfile = "3.19.1"

[package]
name = "llama-buddy"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true }
http-extra = { workspace = true }
tempfile = { workspace = true }
reqwest = { workspace = true, features = ["http2", "gzip", "rustls-tls"] }
tracing = { workspace = true }
tracing-subscriber = "0.3.19"
