[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive", "wrap_help"] }
sys-extra = { path = "crates/sys-extra", default-features = false }
http-extra = { path = "crates/http-extra" }
reqwest = { version = "0.12", default-features = false, features = ["http2", "macos-system-configuration", "charset", "cookies", "socks", "hickory-dns", "rustls-tls"] }
thiserror = "2"
tempfile = "3.19.1"
tracing = "0.1.41"
tokio = "1"

[package]
name = "llama-buddy"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
sys-extra = { workspace = true, features = ["dir", "target"] }
http-extra = { workspace = true }
reqwest = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["std"] }
tempfile = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3.19"
url = { version = "2.5.4", default-features = false, features = ["serde"] }
