[package]
name = "http-extra"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
dir-extra = { workspace = true }
form_urlencoded = "1.2.1"
rand = "0.9.0"
reqwest = { workspace = true, features = ["http2", "gzip", "rustls-tls"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
tempfile = { workspace = true }

