[package]
name = "http-extra"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"

[dependencies]
dir-extra = { workspace = true }
form_urlencoded = "1.2.1"
reqwest = { version = "0.12.15", default-features = false, features = ["http2", "gzip", "rustls-tls"] }
thiserror = { workspace = true }
tokio = { version = "1.44.1", features = ["full"] }
